-- Extensions MVP final. À appliquer après le schéma initial.
-- Ce fichier est idempotent pour faciliter les déploiements.
do $$ begin create type public.progress_claim_status as enum ('draft','submitted','approved','partially_paid','paid','rejected'); exception when duplicate_object then null; end $$;
do $$ begin create type public.payment_method as enum ('bank_transfer','cash','cheque','mobile_money','other'); exception when duplicate_object then null; end $$;
create table if not exists public.progress_claims(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,claim_number text not null,period_start date,period_end date,issue_date date not null default current_date,status public.progress_claim_status not null default 'draft',gross_amount numeric(18,2) not null default 0,retention_rate numeric(8,3) not null default 5,retention_amount numeric(18,2) not null default 0,advance_repayment numeric(18,2) not null default 0,other_deductions numeric(18,2) not null default 0,tax_rate numeric(8,3) not null default 20,tax_amount numeric(18,2) not null default 0,net_amount numeric(18,2) not null default 0,notes text,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,claim_number));
create table if not exists public.progress_claim_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,progress_claim_id uuid not null references public.progress_claims(id) on delete cascade,position integer not null default 0,designation text not null,unit text not null,contract_quantity numeric(18,3) not null default 0,unit_price numeric(18,2) not null default 0,previous_quantity numeric(18,3) not null default 0,current_quantity numeric(18,3) not null default 0,created_at timestamptz not null default now());
create table if not exists public.payments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,project_id uuid references public.projects(id) on delete set null,progress_claim_id uuid references public.progress_claims(id) on delete set null,payment_date date not null default current_date,amount numeric(18,2) not null check(amount>=0),method public.payment_method not null default 'bank_transfer',reference text,notes text,created_by uuid not null references auth.users(id),created_at timestamptz not null default now());
alter table public.progress_claims enable row level security;alter table public.progress_claim_items enable row level security;alter table public.payments enable row level security;
do $$ begin create policy progress_claims_all_org on public.progress_claims for all to authenticated using(exists(select 1 from public.organization_members m where m.organization_id=progress_claims.organization_id and m.user_id=(select auth.uid()) and m.active)) with check(exists(select 1 from public.organization_members m where m.organization_id=progress_claims.organization_id and m.user_id=(select auth.uid()) and m.active)); exception when duplicate_object then null; end $$;
do $$ begin create policy progress_claim_items_all_org on public.progress_claim_items for all to authenticated using(exists(select 1 from public.organization_members m where m.organization_id=progress_claim_items.organization_id and m.user_id=(select auth.uid()) and m.active)) with check(exists(select 1 from public.organization_members m where m.organization_id=progress_claim_items.organization_id and m.user_id=(select auth.uid()) and m.active)); exception when duplicate_object then null; end $$;
do $$ begin create policy payments_all_org on public.payments for all to authenticated using(exists(select 1 from public.organization_members m where m.organization_id=payments.organization_id and m.user_id=(select auth.uid()) and m.active)) with check(exists(select 1 from public.organization_members m where m.organization_id=payments.organization_id and m.user_id=(select auth.uid()) and m.active)); exception when duplicate_object then null; end $$;
grant select,insert,update,delete on public.progress_claims,public.progress_claim_items,public.payments to authenticated;
